document.write(
	"<ul>"
  		+"<li>"
  			+"<a href='index.html'>"
  			+"Home"
  			+"<div class='wave'></div>"
  			+"</a>"	
  		+"</li>"
  		+"<li>"
  			+"<a href='solutions.html'>"
  			+"<p id='solutions'>Solutions</p>"
  			+"<div class='wave'></div>"
  			+"</a>"	
  		+"<li>"
  			+"<a href='aboutus.html'>"
  			+"About us"
  			+"<div class='wave'></div>"
  			+"</a>"	
  		+"</li>"
  		+"<li>"
  			+"<a href='contacts.html'>"
  			+"<p id='contacts'>Contacts</p>"
  			+"<div class='wave'></div>"
  			+"</a>"	
  		+"</li>"
	+"</ul>"

	+"<hr>"
); 