document.write(
	"<ul>"
  		+"<li>"
  			+"<a href='index.html'>"
  			+"Home"
  			+"<div class='wave'></div>"
  			+"</a>"	
  		+"</li>"
  		+"<li>"
  			+"<a href='solutions.html'>"
  			+"Solutions"
  			+"<div class='wave'></div>"
  			+"</a>"	
  		+"<li>"
  			+"<a href='aboutus.html'>"
  			+"About us"
  			+"<div class='wave'></div>"
  			+"</a>"	
  		+"</li>"
  		+"<li>"
  			+"<a id='contacts' href='contacts.html'>"
  			+"Contacts"
  			+"<div class='wave'></div>"
  			+"</a>"	
  		+"</li>"
	+"</ul>"

	+"<hr>"
); 