document.write(
	"<ul>"
  		+"<li>"
  			+"<a href='index.html' class='navbar-button'>"
  			+"Начало"
  			+"<div class='wave'></div>"
  			+"</a>"	
  		+"</li>"
  		+"<li>"
  			+"<a href='solutions.html' class='navbar-button'>"
  			+"<p id='solutions'>Решения</p>"
  			+"<div class='wave'></div>"
  			+"</a>"	
  		+"<li>"
  			+"<a href='aboutus.html' class='navbar-button'>"
  			+"<p id='aboutus'>За нас</p>"
  			+"<div class='wave'></div>"
  			+"</a>"	
  		+"</li>"
  		+"<li>"
  			+"<a href='contacts.html' class='navbar-button'>"
  			+"<p id='contacts'>Контакти</p>"
  			+"<div class='wave'></div>"
  			+"</a>"	
  		+"</li>"
	+"</ul>"

	+"<hr>"
); 